### ISSUE TITLE
Migration to Transformers version 4.x

### ISSUE THREAD

**Issue by zakhan4** [PrimerAI/blanc#14]
Hi,

It would be great if the current blanc implementation could be adjusted to work with Transformer Version 4.x, as it is failing due to some breaking changes!

https://huggingface.co/transformers/migration.html

Thanks!

**Comment by OlegVasilyev4096** [comment]
Thanks! We'll fix this

**Comment by OlegVasilyev4096** [comment]
Seems deprecation of 'masked_lm_labels' was the only issue, other breaking changes were already in. Works for transformers 4.x including 4.6.1. Let us know if anything else, thanks.
