### ISSUE TITLE
How can we use the code to give aspect scores?

### ISSUE THREAD

**Issue by cc-githubaccount** [PrimerAI/blanc#32]
At the bottom of the repo and in the paper, blanc gives the aspect correlation like fluency and consistency, but how can we compute that kind of correlation? My understanding is that blanc can calculate a quality score, and the fluency correlation and consistency correlation are calculated by the same given by blanc with different aspect scores annotated by humans. Is my understanding correct?

**Comment by OlegVasilyev4096** [comment]
Yes, your understanding is correct: blanc gives one single score (supposedly focused on context). We can then measure correlation of this score with any human-scored aspect of quality.
Another measure provided here - estime - can give separate scores - one for consistency and fluency, and another for coherence.

**Comment by cc-githubaccount** [comment]
Thanks a lot!
