### ISSUE TITLE
version.json is not packaged with the source code

### ISSUE THREAD

**Issue by romanwerpachowski** [PrimerAI/blanc#39]
#37 introduced a problem when building e.g. a wheel package: the new version.json file is not packaged with the rest of the code.

#38 fixes that.

**Comment by OlegVasilyev4096** [comment]
Thanks for reminder, I updated the PyPI (thought to add more eval options before the update, left for later).
For now closing, let me know if more problems, thanks again

**Comment by romanwerpachowski** [comment]
What about the pull request #38? Is it unnecessary now?
