### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by Elshan777** [PrimerAI/blanc#41]
when I try to import blanc after pip installing it 
`from blanc import BlancHelp, BlancTune`

I face the error below whether it is in google colab, local, or even in CLI

`FileNotFoundError                         Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8508/2694449195.py in <module>
----> 1 from blanc import BlancHelp, BlancTune

~\anaconda3\lib\site-packages\blanc\__init__.py in <module>
----> 1 from .__version__ import __version__
      2 from .blanc import BlancHelp, BlancTune
      3 from .estime import Estime
      4 from .shannon import Shannon

~\anaconda3\lib\site-packages\blanc\__version__.py in <module>
      2 import os
      3 
----> 4 with open(os.path.join(os.path.dirname(__file__), "version.json")) as reader:
      5     __version__ = json.load(reader)["version"]

**FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\elsha\\anaconda3\\lib\\site-packages\\blanc\\version.json'`**

I was running the same notebook a few weeks ago and did not face with such problem

**Comment by OlegVasilyev4096** [comment]
Thanks, it is messed up now with version, hope to fix soon

**Comment by OlegVasilyev4096** [comment]
Set version simple, installs ok now. Thanks again, let me know if any problems
